/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itla.cobros;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author edgar
 */
public class MainFrame extends javax.swing.JFrame {

    DataBase dataBase = new DataBase();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setAllFieldsTrueOrFalse(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        lbCuenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbCedula = new javax.swing.JLabel();
        fieldCuenta = new javax.swing.JTextField();
        fieldCedula = new javax.swing.JTextField();
        fieldNombres = new javax.swing.JTextField();
        fieldApellidos = new javax.swing.JTextField();
        fieldContrato = new javax.swing.JTextField();
        fieldTel1 = new javax.swing.JTextField();
        fieldTel2 = new javax.swing.JTextField();
        fieldZona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fieldMonto = new javax.swing.JTextField();
        fieldEmpresa = new javax.swing.JTextField();
        fieldDisposicion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaObservacion = new javax.swing.JTextArea();
        fieldRecordatorio = new javax.swing.JTextField();
        fieldFechaContrato = new javax.swing.JTextField();
        fieldDescripcionRecordatorio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fieldDir1 = new javax.swing.JTextField();
        fieldDir2 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenuArchivo = new javax.swing.JMenu();
        btnMenuImportarCuenta = new javax.swing.JMenuItem();
        btnMenuSalir = new javax.swing.JMenuItem();
        btnMenuVer = new javax.swing.JMenu();
        btnMenuMisAsignacionesPendientes = new javax.swing.JMenuItem();
        btnMenuMisAsignacionesYaRealizadas = new javax.swing.JMenuItem();
        btnMenuMisEmpresas = new javax.swing.JMenuItem();
        btnMenuMisRecordatorios = new javax.swing.JMenuItem();
        btnMenuMiPerfilDeUsuario = new javax.swing.JMenuItem();
        btnMenuTrackCuentaActual = new javax.swing.JMenuItem();
        btnMenuMisZonas = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Window");

        jInternalFrame1.setTitle("Cuenta");
        jInternalFrame1.setToolTipText("");
        jInternalFrame1.setVisible(true);

        lbCuenta.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        lbCuenta.setText("Cuenta No.");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel2.setText("Cédula:");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel3.setText("Nombres:");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel4.setText("Apellidos:");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel5.setText("Contrato No.");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel6.setText("Tel. 1:");

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel7.setText("Tel 2:");

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel8.setText("Zona:");

        fieldCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCedulaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel1.setText("Monto:");

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel9.setText("Empresa:");

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel10.setText("Fecha Contrato:");

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel11.setText("Observación:");

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel12.setText("Disposición:");

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel13.setText("Recordatorio:");

        jLabel14.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel14.setText("Descripción");

        textAreaObservacion.setColumns(20);
        textAreaObservacion.setRows(5);
        textAreaObservacion.setName(""); // NOI18N
        jScrollPane1.setViewportView(textAreaObservacion);

        jLabel16.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel16.setText("Dirección L1:");

        jLabel17.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel17.setText("Dirección L2:");

        org.jdesktop.layout.GroupLayout jInternalFrame1Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel7)
                            .add(jLabel8))
                        .add(7, 7, 7)
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(fieldTel1)
                            .add(fieldTel2)
                            .add(fieldZona)
                            .add(fieldContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lbCuenta)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel4))
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jInternalFrame1Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(fieldCedula, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, fieldNombres, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, fieldApellidos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, fieldCuenta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jInternalFrame1Layout.createSequentialGroup()
                            .add(jLabel17)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(fieldDir2))
                        .add(jInternalFrame1Layout.createSequentialGroup()
                            .add(jLabel16)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(fieldDir1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel9)
                    .add(jLabel10)
                    .add(jLabel11)
                    .add(jLabel12)
                    .add(jLabel13)
                    .add(jLabel14))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(fieldRecordatorio)
                    .add(fieldDisposicion)
                    .add(fieldFechaContrato)
                    .add(fieldEmpresa)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(fieldDescripcionRecordatorio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .add(fieldMonto))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbCedula, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(lbCedula))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jInternalFrame1Layout.createSequentialGroup()
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(lbCuenta)
                                    .add(fieldCuenta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel1))
                                .add(6, 6, 6)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel2)
                                    .add(fieldCedula, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel9))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel3)
                                    .add(fieldNombres, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel4)
                                    .add(fieldApellidos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel5)
                                    .add(fieldContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel6)
                                    .add(fieldTel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel7)
                                    .add(fieldTel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel8)
                                    .add(fieldZona, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel16)
                                    .add(fieldDir1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel17)
                                    .add(fieldDir2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(fieldDescripcionRecordatorio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jInternalFrame1Layout.createSequentialGroup()
                                .add(fieldMonto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(6, 6, 6)
                                .add(fieldEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel10)
                                    .add(fieldFechaContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jInternalFrame1Layout.createSequentialGroup()
                                        .add(jLabel11)
                                        .add(0, 0, Short.MAX_VALUE))
                                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel12)
                                    .add(fieldDisposicion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel13)
                                    .add(fieldRecordatorio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(26, 26, 26)))
                        .add(0, 42, Short.MAX_VALUE))))
        );

        jToggleButton1.setText("Siguiente");

        jLabel15.setForeground(new java.awt.Color(0, 204, 51));
        jLabel15.setText("esantiago");

        btnEditar.setText("Editar on");
        btnEditar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnEditarItemStateChanged(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");

        btnMenuArchivo.setText("Archivo");

        btnMenuImportarCuenta.setText("Importar cuenta");
        btnMenuImportarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuImportarCuentaActionPerformed(evt);
            }
        });
        btnMenuArchivo.add(btnMenuImportarCuenta);

        btnMenuSalir.setText("Salir");
        btnMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSalirActionPerformed(evt);
            }
        });
        btnMenuArchivo.add(btnMenuSalir);

        jMenuBar1.add(btnMenuArchivo);

        btnMenuVer.setText("Ver");

        btnMenuMisAsignacionesPendientes.setText("Mis Asignaciones Pendientes");
        btnMenuMisAsignacionesPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMisAsignacionesPendientesActionPerformed(evt);
            }
        });
        btnMenuVer.add(btnMenuMisAsignacionesPendientes);

        btnMenuMisAsignacionesYaRealizadas.setText("Mis Asignaciones Ya Realizadas");
        btnMenuMisAsignacionesYaRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMisAsignacionesYaRealizadasActionPerformed(evt);
            }
        });
        btnMenuVer.add(btnMenuMisAsignacionesYaRealizadas);

        btnMenuMisEmpresas.setText("Mis Empresas");
        btnMenuMisEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMisEmpresasActionPerformed(evt);
            }
        });
        btnMenuVer.add(btnMenuMisEmpresas);

        btnMenuMisRecordatorios.setText("Mis Recordatorios");
        btnMenuMisRecordatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMisRecordatoriosActionPerformed(evt);
            }
        });
        btnMenuVer.add(btnMenuMisRecordatorios);

        btnMenuMiPerfilDeUsuario.setText("Mi Perfil De Usuario");
        btnMenuMiPerfilDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMiPerfilDeUsuarioActionPerformed(evt);
            }
        });
        btnMenuVer.add(btnMenuMiPerfilDeUsuario);

        btnMenuTrackCuentaActual.setText("Track Cuenta Actual");
        btnMenuTrackCuentaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuTrackCuentaActualActionPerformed(evt);
            }
        });
        btnMenuVer.add(btnMenuTrackCuentaActual);

        btnMenuMisZonas.setText("Mis Zonas");
        btnMenuMisZonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMisZonasActionPerformed(evt);
            }
        });
        btnMenuVer.add(btnMenuMisZonas);

        jMenuBar1.add(btnMenuVer);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1)
                    .add(jInternalFrame1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jToggleButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, btnEditar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel15)
                .add(144, 144, 144)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jInternalFrame1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnEditar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jToggleButton1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuImportarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuImportarCuentaActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = CuadroSelectorArchivos.initFileChooser();

        if (fc != null) {
            String path = fc.getCurrentDirectory().toString();
            String name = fc.getSelectedFile().getName();

            List cuenta = new ArrayList();
            cuenta = CargarProperties.getCaso(path, name);

            for (Object obj : cuenta) {
                System.out.print(obj);
                System.out.print(",");
            }

            actualizarFields(cuenta);

        }







    }//GEN-LAST:event_btnMenuImportarCuentaActionPerformed

    public void actualizarFields(List cuentaActual) {

        fieldCuenta.setText(cuentaActual.get(0).toString());
        fieldCedula.setText(cuentaActual.get(1).toString());
        fieldNombres.setText(cuentaActual.get(2).toString());
        fieldApellidos.setText(cuentaActual.get(3).toString());
        fieldContrato.setText(cuentaActual.get(4).toString());
        fieldTel1.setText(cuentaActual.get(5).toString());
        fieldTel2.setText(cuentaActual.get(6).toString());
        fieldZona.setText(cuentaActual.get(7).toString());
        fieldDir1.setText(cuentaActual.get(8).toString());
        fieldDir2.setText(cuentaActual.get(9).toString());
        fieldMonto.setText(cuentaActual.get(10).toString());
        fieldEmpresa.setText(cuentaActual.get(11).toString());
        fieldFechaContrato.setText(cuentaActual.get(12).toString());
        textAreaObservacion.setText(cuentaActual.get(13).toString());
        fieldDisposicion.setText(cuentaActual.get(14).toString());
        fieldRecordatorio.setText(cuentaActual.get(15).toString());
        fieldDescripcionRecordatorio.setText(cuentaActual.get(16).toString());








    }

    private void btnMenuMisAsignacionesYaRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMisAsignacionesYaRealizadasActionPerformed
        // TODO add your handling code here:
        IniciarReporte iniciarReporte = new IniciarReporte();
        try {
            iniciarReporte.ejecutarReporte("MisAsignacionesYaRealizadas");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR 408: No se pudo cargar el reporte", "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMenuMisAsignacionesYaRealizadasActionPerformed

    private void btnMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSalirActionPerformed
        // TODO add your handling code here:


        System.exit(0);


    }//GEN-LAST:event_btnMenuSalirActionPerformed

    private void btnMenuMiPerfilDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMiPerfilDeUsuarioActionPerformed
        // TODO add your handling code here:
        //Reporte repo = new Reporte();
        IniciarReporte iniciarReporte = new IniciarReporte();
        try {
            iniciarReporte.ejecutarReporte("Agente2");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR 408: No se pudo cargar el reporte", "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMenuMiPerfilDeUsuarioActionPerformed

    private void btnMenuMisZonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMisZonasActionPerformed
        // TODO add your handling code here:
        IniciarReporte iniciarReporte = new IniciarReporte();
        try {
            iniciarReporte.ejecutarReporte("MisZonas");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR 408: No se pudo cargar el reporte", "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMenuMisZonasActionPerformed

    private void btnMenuTrackCuentaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuTrackCuentaActualActionPerformed
        // TODO add your handling code here:
        IniciarReporte iniciarReporte = new IniciarReporte();
        try {
            iniciarReporte.ejecutarReporte("TrackCuenta");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR 408: No se pudo cargar el reporte", "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMenuTrackCuentaActualActionPerformed

    private void btnMenuMisRecordatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMisRecordatoriosActionPerformed
        // TODO add your handling code here:
        IniciarReporte iniciarReporte = new IniciarReporte();
        try {
            iniciarReporte.ejecutarReporte("MisRecordatorios");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR 408: No se pudo cargar el reporte", "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMenuMisRecordatoriosActionPerformed

    private void btnMenuMisEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMisEmpresasActionPerformed
        // TODO add your handling code here:
        IniciarReporte iniciarReporte = new IniciarReporte();
        try {
            iniciarReporte.ejecutarReporte("MisEmpresas");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR 408: No se pudo cargar el reporte", "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMenuMisEmpresasActionPerformed

    private void btnMenuMisAsignacionesPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMisAsignacionesPendientesActionPerformed
        // TODO add your handling code here:
        IniciarReporte iniciarReporte = new IniciarReporte();
        try {
            iniciarReporte.ejecutarReporte("MisAsignacionesPendientes");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR 408: No se pudo cargar el reporte", "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMenuMisAsignacionesPendientesActionPerformed

    private void fieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCedulaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed
    private void setAllFieldsTrueOrFalse(boolean b) {

            fieldApellidos.setEditable(b);
            fieldCedula.setEditable(b);
            fieldContrato.setEditable(b);
            fieldCuenta.setEditable(b);
            fieldDescripcionRecordatorio.setEditable(b);
            fieldDisposicion.setEditable(b);
            fieldEmpresa.setEditable(b);
            fieldFechaContrato.setEditable(b);
            fieldMonto.setEditable(b);
            fieldNombres.setEditable(b);
            fieldRecordatorio.setEditable(b);
            fieldTel1.setEditable(b);
            fieldTel2.setEditable(b);
            fieldZona.setEditable(b);
            fieldDir1.setEditable(b);
            fieldDir2.setEditable(b);
            textAreaObservacion.setEditable(b);
  }
    

    private void btnEditarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnEditarItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            btnEditar.setText("Editar off");
            setAllFieldsTrueOrFalse(true);
        } else {
            btnEditar.setText("Editar on");
            setAllFieldsTrueOrFalse(false);
        }
    }//GEN-LAST:event_btnEditarItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JMenu btnMenuArchivo;
    private javax.swing.JMenuItem btnMenuImportarCuenta;
    private javax.swing.JMenuItem btnMenuMiPerfilDeUsuario;
    private javax.swing.JMenuItem btnMenuMisAsignacionesPendientes;
    private javax.swing.JMenuItem btnMenuMisAsignacionesYaRealizadas;
    private javax.swing.JMenuItem btnMenuMisEmpresas;
    private javax.swing.JMenuItem btnMenuMisRecordatorios;
    private javax.swing.JMenuItem btnMenuMisZonas;
    private javax.swing.JMenuItem btnMenuSalir;
    private javax.swing.JMenuItem btnMenuTrackCuentaActual;
    private javax.swing.JMenu btnMenuVer;
    private javax.swing.JTextField fieldApellidos;
    private javax.swing.JTextField fieldCedula;
    private javax.swing.JTextField fieldContrato;
    private javax.swing.JTextField fieldCuenta;
    private javax.swing.JTextField fieldDescripcionRecordatorio;
    private javax.swing.JTextField fieldDir1;
    private javax.swing.JTextField fieldDir2;
    private javax.swing.JTextField fieldDisposicion;
    private javax.swing.JTextField fieldEmpresa;
    private javax.swing.JTextField fieldFechaContrato;
    private javax.swing.JTextField fieldMonto;
    private javax.swing.JTextField fieldNombres;
    private javax.swing.JTextField fieldRecordatorio;
    private javax.swing.JTextField fieldTel1;
    private javax.swing.JTextField fieldTel2;
    private javax.swing.JTextField fieldZona;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbCuenta;
    private javax.swing.JTextArea textAreaObservacion;
    // End of variables declaration//GEN-END:variables
}
